### ISSUE TITLE
Chronic rsync failures cause update to run over time

### ISSUE THREAD

**Issue by ketiltrout** [radiocosmology/alpenhorn#101]
This continue:

https://github.com/radiocosmology/alpenhorn/blob/b64b6e3eeb3dfd40588f4726eedd7f8db92c2f25/alpenhorn/update.py#L437

is problematic in that it can cause the loop over copy requests to go over time because it skips the over-time check at the end of the loop.

I've seen this in the `cedar -> niagara` pull when `cedar`'s filesystem is messed up (which happens more often than it should).  The `rsync` can take minutes before it fails (presumably by timing out).  When the number of files to transfer is large, `niagara`'s alpenhorn gets stuck for _hours_ in a single update loop.

(The over-time check is supposed to prohibit spending more than five minutes at a time transferring files.)

The easiest solution is probably to just move the over-time check to the top of the loop from the bottom, then it will always be checked.

**Comment by cubranic** [comment]
@ketiltrout fix is in PR #112.
