### ISSUE TITLE
Catch-22 when `alpenhorn activate`-ing a node

### ISSUE THREAD

**Issue by cubranic** [radiocosmology/alpenhorn#113]
`alpenhorn.activate` includes the following check:
```
    if not util.alpenhorn_node_check(node):
        click.echo('Node "{}" does not match ALPENHORN_NODE'.format(node.name))
```
but `util.alpenhorn_node_check` does not even check the contents of ALPENHORN_NODE if the node is not active:
```
def alpenhorn_node_check(node):
    """Returns True if ALPENHORN_NODE contains node name"""

    if node.active:
        file_path = os.path.join(node.root, 'ALPENHORN_NODE')
        if os.path.isfile(file_path):
            with open(file_path, 'r') as f:
                first_line = f.readline()
                # Check if the actual node name is in the textfile
                if node.name == first_line.rstrip():
                    # Great! Everything is as expected.
                    return True

    return False
```

**Comment by cubranic** [comment]
Either we need to remove the check for activity from `util.alpenhorn_node_check` (in which case it will have to be done by its callers), or we add to it an argument as a flag whether to do it.

(I'm leaning towards the former.)

**Comment by ketiltrout** [comment]
Yes, removing the `node.active` check makes sense.  The onus is on the caller to figure out why `alpenhorn_node_check` failed.

**Comment by cubranic** [comment]
Well, what I suggest is to have only one way alpenhorn-node-check can fail, and that’s because the APLENHORN_NODE file is not present or correct. It won’t care about node.active, that’s for the caller to deal with, as appropriate.
