### ISSUE TITLE
'format-transport' requires additional manual steps before it can be mounted

### ISSUE THREAD

**Issue by cubranic** [radiocosmology/alpenhorn#115]
1. the new disk is not added to /etc/fstab: "mount: can't find /mnt/CH-ZAD7JVXH in /etc/fstab"
2. once this is fixed, when running "mount-transport", the ALPENHORN_NODE file is missing.

**Comment by cubranic** [comment]
I'm not sure if `format-transport` or anything else should run those steps itself, but for sure they should be documented, rather than suggesting to just "mount-transport".

**Comment by ketiltrout** [comment]
Creating the ALPENHORN_NODE file can be accomplished with `node init` now (#237)

But the "transport" command group has been removed as out-of-scope.  See #240
