### ISSUE TITLE
Leaving node address empty (null) will cause it never to match any copy requests

### ISSUE THREAD

**Issue by cubranic** [radiocosmology/alpenhorn#117]
We should have a sensible default for the address if `--address` is not given in `client.activate`. Otherwise, it's left as NULL and the following line in the `update.update_node_requests` (line 289) will not match any requests where that such a node is the `from_node`.

```
    # Add in constraint that node_from cannot be an HPSS node
    requests = requests.join(st.StorageNode).where(st.StorageNode.address != 'HPSS')
```

**Comment by ketiltrout** [comment]
Fixed by #153
