### ISSUE TITLE
Check SQL used in `client.status` for inefficiencies

### ISSUE THREAD

**Issue by cubranic** [radiocosmology/alpenhorn#120]
`alpenhorn status` takes 59s on the FRB archive already. :disappointed: We should look over the SQL it’s using and see if anything can be optimized there.

**Comment by cubranic** [comment]
Instead of joining with ArchiveFile just to get its size, we can get size directly from the "size on disk" column in the ArchiveFileCopy table, now that it's available.

**Comment by ketiltrout** [comment]
`node stats` re-implements the old `status` command.  I'm going to assume that fixes this.

We should open new issues for new inefficiencies found in the new CLI.
