### ISSUE TITLE
Break up client into `noun verb` subcommands

### ISSUE THREAD

**Issue by cubranic** [radiocosmology/alpenhorn#122]
As discussed on Slack, the current list of client commands is getting long, and it would only get worse if we added more. (And we do, for instance for inspecting or modifying various minor aspects of the objects in the database -- e.g., listing the nodes' names, or changing their description, etc. -- without needing to do it in SQL.) The natural solution would be to break it down into subcommands, probably of the "noun verb" variety: `node list`, `node create`, `node modify`, etc. (This is similar to what we already do in data-flagging tools.)

There is the question of whether to use "noun verb" or "verb noun" pattern for naming. I don't know if there is a generally accepted principle: for example Git offers "noun verb", when it does have subcommands (e.g., "branch" or "remote"). I think in this case using "noun verb" works a better, just because Nodes, Acquisitions, and ArchiveFiles objects are so central, and everything else about the code revolves around them. With that in mind, here is a proposal:

- node: create, list, modify, status(?)
- acq(uisition): import, list, info, (?)
- archive/file: ...
- transport: list, mount, unmount?

Do we need to keep all the existing commands, for backward compatibility? With a plan to deprecate them?

**Comment by jrs65** [comment]
I vote for noun verb. That's why I opted for in the last few CLI tools I wrote (`cdf` and `chp`) and it seems like that's considered better in the wider world.

**Comment by jrs65** [comment]
Also, your list looks great to me.

I do wonder how we should fit the `sync` command in there. It unfortunately works across multiple nouns (as it sync from group to node). Probably it should slot under `node`. We also need to add the `clean` command under node.

**Comment by jrs65** [comment]
You might consider trying to split the different nouns into different files too. It's pretty unwieldy at the moment.

**Comment by cubranic** [comment]
I've already started on splitting up client.py even without the subcommands, it was getting too long to work with.

I'm OK with still having top-level commands for big operations, or even the most common ones. (I'm not sure what they'd be right now, other than "init", maybe. "status" and "sync"?)

**Comment by cubranic** [comment]
Hmm, the drawback of this scheme is that almost everything in the CLI is node-related. :-)
