### ISSUE TITLE
Refactor duplicate config+db+extension code into a single function

### ISSUE THREAD

**Issue by cubranic** [radiocosmology/alpenhorn#20]
We have the same code for to load the config, start the database, and register extensions duplicated in a couple of places. (Right now it's in `alpenhorn.client` in `_init_config_db` and `init`, as well as `alpenhorn.service` in `cli`.)  Can we refactor it into a function in `alpenhorn/__init__`?

Leaving out the comments, this is the same set of steps that always (should? must?) happen:
```python
    config.load_config()
    extensions.load_extensions()
    db.config_connect()
    extensions.register_type_extensions()
```

**Comment by jrs65** [comment]
I did have a bit of a think about this. Combining them all isn’t super trivial as the code in client.init needs to do extra steps in between (i.e. creating various tables), that none of the other sections should attempt to do (of course those could just be wrapped in an `if create:` statement, where `create` is some argument on the function).

**Comment by cubranic** [comment]
You’re right, I missed the bit with table creation in client.init. But there is still the duplication in client._init_config_db and service.cli. We could move _init_config_db to db module and let “client.init” keeps its own flow, which makes sense since it’s a special case.

And since the create_tables is run with “safe=True”, is there any harm in running it when the tables already exist? Does it fail or just silently no-op? (Sorry, typing while offline so can’t lookup the docs.)

**Comment by jrs65** [comment]
I think your suggestion for how to do it makes sense. There'll probably be more places that we want to load the `db` from eventually.

I think with `safe=True` there is no harm. However I wanted table creation to be an explicit operation that you have to perform, so it needs to have it's own code path for that.
