### ISSUE TITLE
Reload alpenhornd configuration / restart observers on HUP

### ISSUE THREAD

**Issue by cubranic** [radiocosmology/alpenhorn#37]
It seems like currently the only option when changing the configuration or the mounted nodes is to restart the service. Can any of this be done on the fly, on receiving SIGHUP?

**Comment by jrs65** [comment]
I think most of the config is scraped dynamically, i.e. it re-evaluates the mounted nodes every time it enters the main loop, but I guess as you say that doesn't work for the observers. We could have it re-check every time that the running observers are consistent with what nodes are mounted. I think this would require a significant shifting of the logic so maybe a big warning to not unmount auto_import nodes would do in the meantime.

**Comment by cubranic** [comment]
What about when a new auto_import node is mounted? I don't think the daemon will add an observer for it, until it's restarted. (That's the main use case I had in mind.)

**Comment by cubranic** [comment]
I missed that dynamic observers on changing auto-import set are already tracked in #15. But there are still a few (mostly minor) things from the config file that could be modified on reload:

- update interval
- auto_import interval
- logging level
- database connection?

I'm not sure if it's technically feasible to make extensions reloadable, but it would be really cool if we could dynamically update filename patterns, too.

**Comment by jrs65** [comment]
I'd also forgotten about that #15. 2017 Richard seemed to be really on the ball. 2018 Richard, not so much.

I'm going to create an issue to track the other things to update. Those are harder, and I'm not sure whether we can/should support them, but let's at least think about it.
