### ISSUE TITLE
Handle acquisitions as nested directories of the root and files in acq subdirs

### ISSUE THREAD

**Issue by cubranic** [radiocosmology/alpenhorn#4]
Desired use case from FRB:

Acqusitions (::= EVT_DIR):
```
<CHIME_FRB_ROOT>/<yyyy>/<mm>/<dd>/<frb|rfi>_<event_id>_<UTCdatetime>/(event details)
```

Data files:
```
EVT_DIR/summary.tx
EVT_DIR/intensity_data/beam_<<beam_no>>/  (repeat for multiple beams)
EVT_DIR/intensity_data/beam_<<beam_no>>/raw/
EVT_DIR/intensity_data/beam_<<beam_no>>/proc/
EVT_DIR/baseband_data/raw/
EVT_DIR/baseband_data/proc/
EVT_DIR/housekeeping_data/
```

**Comment by jrs65** [comment]
Great. I guess we can pretty easily put together a series of tests based on that kind of scheme. The generic handlers should be able to deal with it easily enough. I think the place we'll get the most issues is when moving files around, where we need to be careful to create all directory levels.

**Comment by cubranic** [comment]
How should we record those intermediate directories in the database? Would an acquisition's be everything between the node.root and whatever the acquisition type decides is the end of the name? Using the example above, this would be something like "2017/03/21/frb_123xz_123456T001122Z". The files's names would then be the path relative to the acquisition, e.g., "summary.txt", "intensity_data/beam_07/raw/some_file.hdf5", and "housekeeping_data/another_file.hd5".

This would keep the schema as-is, but on the other hand requires the acquisition type to tell us what the acquisition name is, given a file's path.

**Comment by cubranic** [comment]
Conclusions reached with @jrs65 yesterday:

- confirmed the above naming plan
- importing a file asks each of the registered acquisition types if the dirname belongs to it. If none can handle it, the rightmost segment of the directory is removed and the process started again.

**Comment by cubranic** [comment]
Note that in [`globre`](https://pypi.python.org/pypi/globre), the glob matching library we use in `generic.py` when the file/acquisition name pattern is a glob, the `*` wildcard excludes the slash, while `**` matches it.
