### ISSUE TITLE
`verify NODE` doesn't verify the files on the actual node

### ISSUE THREAD

**Issue by cubranic** [radiocosmology/alpenhorn#44]
If _NODE_ is not mounted on the host where `verify` is run, but happens to use the same root as a another node that's actually mounted on the host, then the command will test the files in the locally mounted node.

We could catch this condition by checking if ALPENHORN_NODE in the root corresponds to the node being verified.

**Comment by jrs65** [comment]
This is a great idea. The first check should indeed be on the `ALPENHORN_NODE` file.
