### ISSUE TITLE
Command to show known corrupt files (was: `verify` should show files already known to be corrupt)

### ISSUE THREAD

**Issue by cubranic** [radiocosmology/alpenhorn#45]
The query to get the file list in `client.verify` has a condition "`ar.ArchiveFileCopy.has_file == 'Y')`", so that known corrupt files will not be shown in the output. This is kind of confusing to the user, as there is no insight into corrupt files.

Furthermore, even the files that were only discovered to be corrupt during the `verify`'s run, and so their `has_file` attribute gets changed from 'Y' to 'X', will disappear from the output if `verify` was run again immediately.

**Comment by cubranic** [comment]
I'd like to expand this to:

- verify: `has_file="Y"` or (`has_file="M"` and `wants_file="Y"`)
- `has_file="X"` could either be included in the summary report without verification (under a separate "known corrupt" heading?) or reverified (maybe activated by a separate option?)

**Comment by ketiltrout** [comment]
`node verify` no longer performs foreground file checking, but instead just requests the daemon do it (see #229). Functionality for listing known corrupt files is being to be moved to to `file` command group.
