### ISSUE TITLE
Copy request fails if `node_from` has a NULL `address`

### ISSUE THREAD

**Issue by cubranic** [radiocosmology/alpenhorn#48]
Line 304 in [`update.py`](https://github.com/radiocosmology/alpenhorn/blob/master/alpenhorn/update.py#L304) is filtering out my list of archive file copy requests to nothing:

```py
    requests = requests.join(st.StorageNode).where(st.StorageNode.address != 'HPSS')
```

It's probably because the request's `node_from.address` is NULL. When I remounted the node with an explicit `--address` argument, the copy went ahead fine.

**Comment by jrs65** [comment]
Oh, that's an important one. We must have changed the logic in the rewrite because alpenhorn 1 doesn't do that. The intended use is that it matches which nodes it's processing solely from the hostname, so if both nodes `host` fields match it should process them.

**Comment by cubranic** [comment]
The code in `client.mount` is identical in alpenhorn v1 and current. There are no restrictions on StorageNode.address` and the default is `None` -- there is no logic to use`StorageNode.host` as the default. But `mount_transport` in `ch_alpenhorn/alpenhorn_chime.py` sets it to `jingle`, maybe that's why you never see it?
