### ISSUE TITLE
What is the purpose of `storage_type` "F"?

### ISSUE THREAD

**Issue by cubranic** [radiocosmology/alpenhorn#49]
The docstring says "'F': for data in the field (i.e acquisition machines)", but I don't see it being checked for anywhere in the code.

**Comment by jrs65** [comment]
That is a reasonable question. There was originally some policy differentiation, but I think that changed  at some point. It's mostly there because those acq nodes shouldn't be marked as transport T, or archive A, so this is just a third category.
