### ISSUE TITLE
Discrepancy in file count between `status` and `mounted`

### ISSUE THREAD

**Issue by cubranic** [radiocosmology/alpenhorn#51]
When reporting the number of files on a storage node, the two commands both use a join query on ArchiveFileCopy and StorageNode, but `status` in addition also filters by `ArchiveFileCopy.has_file=='Y'`.

The discrepancy can be quite large: right now on tubular, `mounted` reports 33,342 files on "gong", and `status` only 13,388.

**Comment by jrs65** [comment]
We think both should just used the `has_file`
