### ISSUE TITLE
Alpenhorn stops registering new files after a while

### ISSUE THREAD

**Issue by ketiltrout** [radiocosmology/alpenhorn#52]
While running in the main loop, after some time alpenhorn stops responding to new files in directories it should be monitoring.

This is fixed by a restart.  After the restart, alpenhorn crawls the directory and finds and registers all the files it missed.

For example, see the time period 12 April 2018 to 10 May 2018 on tubular.

**Comment by jrs65** [comment]
I don't think we currently understand why this happens, so a bit more investigation is needed.

**Comment by ketiltrout** [comment]
Ah! no.  I fixed this in alpenhorn1 in summer.  The problem was there was no callback for `on_created`.

Here: https://bitbucket.org/chime/alpenhorn/commits/8d411946b55900364d52bbc057d7e1d99fc66da4

**Comment by jrs65** [comment]
Okay so we just need to make sure we forward port this fix.

**Comment by ketiltrout** [comment]
Okay, two things:

1. My previous comment is wrong: that fixed a different bug<sup>†</sup> (which we should still make sure we port to alpenhorn2)
2. Based on the observer lock-up on 2 December, it seems likely that what's going on is a DB I/O connection is hanging forever.  (the same problem that underlies chime-experiment/infrastructure#41 )

----
† The bug being that the observer seemed to be ignoring some files at random

**Comment by cubranic** [comment]
1. Handling "on_created" is already in alpenhorn2: [auto_import.py#263](../blob/master/alpenhorn/auto_import.py#L263).

2. Should we close this until we reproduce the lock-up in Alpenhorn2?

**Comment by jrs65** [comment]
Yeah. I'd agree with doing that.
