### ISSUE TITLE
File changes are unnoticed between the initial storage crawl and the start of observers

### ISSUE THREAD

**Issue by cubranic** [radiocosmology/alpenhorn#53]
When the Alpenhorn service starts, it first crawls files in the existing directories, and then registers observers on filesystem changes in storage node's root directories (and below). (See [`auto_import.setup_observers`](https://github.com/radiocosmology/alpenhorn/blob/master/alpenhorn/auto_import.py#L291).)

If the crawling takes a long time (after a restart today it's been going on for the past six hours), there is a hole during which changes will not be registered until the next restart and crawl through mounted storage nodes.

**Comment by jrs65** [comment]
I imagine we could just reverse the order, i.e. set up the observers first, and the commence the crawl. The crawl could even be spawned in a background thread, I can't see how it needs to be a blocking operation.

**Comment by cubranic** [comment]
Maybe for this issue we just consider reversing the order of observer setup and filesystem crawl, and let background work be done under #75?
