### ISSUE TITLE
Add a file size field to ArchiveFileCopy

### ISSUE THREAD

**Issue by cubranic** [radiocosmology/alpenhorn#58]
This would record the "true" size, as used by the filesystem. (E.g., accounting for holes in sparse files or Lustre filesystem compression.) @ketiltrout is planning on adding it to alpenhorn1, and we should port it here as well.

**Comment by cubranic** [comment]
@ketiltrout should I have a look at implementing this? I'd expect we'll deploy Alpenhorn2 soon on FRB archiver and I'd like to have the schema as stable as possible before that.

**Comment by jrs65** [comment]
There's a few other schema proposals you might consider adding in there too: #62 #56

**Comment by cubranic** [comment]
@ketiltrout is the true size available from `os.stat` as attribute `st_blocks` (multiplied by 512 for the size in bytes)?

**Comment by cubranic** [comment]
PR #107 @ketiltrout
