### ISSUE TITLE
Allow multiple storage nodes to be specified with --target for "alpenhorn clean"

### ISSUE THREAD

**Issue by ketiltrout** [radiocosmology/alpenhorn#65]
In a few instances, it would convenient to be able to specify multiple targets with the `clean` command, which would then restrict cleaning to only files with copies on _all_ targets.

For example, files on `cedar_staging` should only be deleted if they're on _both_ `cedar_archive` and `scinet_hpss`.  Currently we only check for a copy on `scinet_hpss`, which works out okay because syncing from `cedar_staging` and `cedar_archive` is a trivial hard link (and, so significantly faster).

I'm okay with either:
```
alpenhorn clean cedar_staging --target=cedar_archive --target=scinet_hpss
```
or
```
alpenhorn clean cedar_staging --target=cedar_archive,scinet_hppss
```

**Comment by cubranic** [comment]
I like either, we should support both if possible.
