### ISSUE TITLE
Add a check that a node is actually mounted on filesystem

### ISSUE THREAD

**Issue by jrs65** [radiocosmology/alpenhorn#7]
An issue we occasionally have with CHIME is that is alpenhorn gets start and a node which is marked as `mounted` in the database is not actually mounted in the filesystem. When this happens any transfers requested from that node end up failing and causing files to be marked as missing.

One idea might be to have a marked in each node the alpenhorn can check for in the directory. Something simple as a requirement to have an ALPENHORN_NODE file sit in the root of the node.

Thoughts? @cubranic

**Comment by jrs65** [comment]
One thing I've just thought of that could be a nice extension of this is that before attempting a transfer, alpenhorn could attempt to fetch the ALPENHORN_NODE file from the source node, and check that it is what it expected (i.e. the node name in @cahofer's current implementation). This would eliminate a whole class of issues that can happen when a remote alpenhorn instance tries to fetch from a node which is not available over the network for some reason. At the moment it marks every file it tries to fetch as `has_file=M` forcing a full md5 check of them for no reason.

**Comment by jrs65** [comment]
I think @cahofer has already fixed this, but I need to check.

**Comment by cubranic** [comment]
The server already included @cahofer's fix from v1, but the "mount" command didn't use it. So I'll add that to this issue as well.
