### ISSUE TITLE
Default hostname differs in `create-node` and `mounted`

### ISSUE THREAD

**Issue by cubranic** [radiocosmology/alpenhorn#71]
My laptop's hostname is `davit.phas.ubc.ca`, as reported by `/bin/hostname`. That's the hostname that's used by `alpenhorn create-node` when I don't specify the `--hostname` option. However, `alpenhornd` and `alpenhorn mounted` see the hostname as being just `davit`. It's a minor problem, but confusing to a new user, and annoying when just trying to quickly create a node on the same host where the daemon is already running.

**Comment by jrs65** [comment]
> I'm thinking the hostname we want just the first part, but should probably use the FQDN for `address`, where that's used.

This.

**Comment by ketiltrout** [comment]
This was already fixed in alpenhorn1, I think in the way you propose:

https://bitbucket.org/chime/alpenhorn/commits/ee612bf102caeafc005b38a034a053c6b16490eb

It used to work as-is, but at some point broke, so I had to fix it.
