### ISSUE TITLE
Run flake8 or pylint as part of Travis-CI run

### ISSUE THREAD

**Issue by cubranic** [radiocosmology/alpenhorn#79]
I just came across a missing import that wasn't caught by the unit tests, but would have been with a code checker like Flake8 or Pylint. Can we run one of those as part of the CI?

**Comment by jrs65** [comment]
I think we should be able to, and I've certainly no objection to doing so. Probably will need to adjust the stylistic settings to something reasonable though.

**Comment by cubranic** [comment]
Even better, we could just go with [_Black_](https://black.readthedocs.io/en/stable/), add it to the editor save hook, and never think about it again.

**Comment by cubranic** [comment]
(Ah wait, Black only auto-formats and doesn't do any syntax checks. Stlll, it might be worth using in combination.)
