### ISSUE TITLE
Make client.import_files work from a nested subdirectory of a root

### ISSUE THREAD

**Issue by cubranic** [radiocosmology/alpenhorn#9]
Currently, `client.import_files` assumes it's running from within root (acq.name is compared against the contents of the current directory). We want to be able to run it from any subdirectory of an arbitrarily nested structure (even subdirectories of an acquisition), and so it needs to know its relative path to the root when checking file (+acq) names.

**Comment by jrs65** [comment]
We need to make sure that `client.import_files` does what we think it should do.

**Comment by cubranic** [comment]
While `import_files` does check that it is within an acquisition when it walks the contents of the current directory ((src)[https://github.com/radiocosmology/alpenhorn/blob/ccf215eb00693e2048e27676c624ad519b1078a5/alpenhorn/client.py#L863]), it compares this relative to its start, instead of the node's root, so the `startswith(acq)` check can't succeed:
```py
        for d, ds, fs in os.walk(os.getcwd()):
            d = os.path.relpath(d)
            if d == '.':            # skip the current directory
                continue
            for acq in db_acqs.keys():
                if d == acq:
                    # the directory is the acquisition
                    acqs.append(d)
                    break
                if d.startswith(acq + "/"):
                    # the directory is inside an acquisition
                    break
                if acq.startswith(d + "/"):
                    # the directory is an acquisition's ancestor
                    break
```

**Comment by cubranic** [comment]
@jrs65 I have an important design question that Alpenhorn v1 didn't have to deal with.

Since acquisitions can contain nested subdirectories, should `import_files` limit itself to only walk the current directory and its descendants?

1. If so, the directory can be inside an acquisition or a parent directory of several acquisitions, but either way we would only consider for import files that are found by `os.walk(cwd)`. If `--acq` option is given, the walk is further restricted to only look at files that would belong to those acquisitions.

2. There is a slightly special case if the current directory inside an acquisition, in which case we could take it to walk the entire acquisition subtree, not just the current directory's.

3. If not, do we traverse starting from the node root? What if the current directory is not in the node root?

FWIW, the original help text for `import_files` says "Scan the current directory for known acquisition files and add them into the database for NODE." So option 1 would be the most natural behaviour, I think.
